version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mediator
      POSTGRES_PASSWORD: mediator
      POSTGRES_DB: mediator
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    env_file: .env
    depends_on: [db]
    ports:
      - "8000:8000"
    command: ["gunicorn", "-w", "2", "-b", "0.0.0.0:8000", "mediator.app:create_app()"]

volumes:
  dbdata:
